@extends('layout')
@section('header')
    @include('partials.web_home.header')
@endsection

@section('content')
    <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium culpa, maxime obcaecati officia repellat sit tenetur! A amet delectus eveniet facilis iusto officia quod, soluta temporibus vel voluptate! Culpa, hic? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam aspernatur commodi consequatur dolorum, eaque eveniet fugiat ipsum iusto magnam maxime minima molestiae nam nisi nulla quasi quia quod, ratione voluptas? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores deserunt distinctio eaque eius itaque magni, molestiae natus, nesciunt nulla numquam placeat quo quod similique! Accusamus consequuntur culpa ex repellendus suscipit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda blanditiis culpa dignissimos dolorum expedita id ipsum libero nisi officiis sit. Debitis incidunt ipsam neque porro qui, quisquam quos reiciendis? Repellat.</div>
    <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium culpa, maxime obcaecati officia repellat sit tenetur! A amet delectus eveniet facilis iusto officia quod, soluta temporibus vel voluptate! Culpa, hic? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam aspernatur commodi consequatur dolorum, eaque eveniet fugiat ipsum iusto magnam maxime minima molestiae nam nisi nulla quasi quia quod, ratione voluptas? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores deserunt distinctio eaque eius itaque magni, molestiae natus, nesciunt nulla numquam placeat quo quod similique! Accusamus consequuntur culpa ex repellendus suscipit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda blanditiis culpa dignissimos dolorum expedita id ipsum libero nisi officiis sit. Debitis incidunt ipsam neque porro qui, quisquam quos reiciendis? Repellat.</div>
    <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium culpa, maxime obcaecati officia repellat sit tenetur! A amet delectus eveniet facilis iusto officia quod, soluta temporibus vel voluptate! Culpa, hic? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam aspernatur commodi consequatur dolorum, eaque eveniet fugiat ipsum iusto magnam maxime minima molestiae nam nisi nulla quasi quia quod, ratione voluptas? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores deserunt distinctio eaque eius itaque magni, molestiae natus, nesciunt nulla numquam placeat quo quod similique! Accusamus consequuntur culpa ex repellendus suscipit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda blanditiis culpa dignissimos dolorum expedita id ipsum libero nisi officiis sit. Debitis incidunt ipsam neque porro qui, quisquam quos reiciendis? Repellat.</div>
    <div>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium culpa, maxime obcaecati officia repellat sit tenetur! A amet delectus eveniet facilis iusto officia quod, soluta temporibus vel voluptate! Culpa, hic? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam aspernatur commodi consequatur dolorum, eaque eveniet fugiat ipsum iusto magnam maxime minima molestiae nam nisi nulla quasi quia quod, ratione voluptas? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores deserunt distinctio eaque eius itaque magni, molestiae natus, nesciunt nulla numquam placeat quo quod similique! Accusamus consequuntur culpa ex repellendus suscipit. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda blanditiis culpa dignissimos dolorum expedita id ipsum libero nisi officiis sit. Debitis incidunt ipsam neque porro qui, quisquam quos reiciendis? Repellat.</div>
@endsection
